# =============================================================
# Lambda@Edge Module — Viewer Request authorizer
# =============================================================
#
# Deploys a Node.js Lambda function in us-east-1 (required by
# CloudFront Lambda@Edge), published with `publish = true` so
# that CloudFront can reference a specific immutable version ARN.
#
# The function source code lives in:
#   lambda/auth-edge/index.js
#
# A config.js is GENERATED here (using templatefile) and zipped
# together with index.js.  This avoids environment variables,
# which are not supported by Lambda@Edge.
#
# Outputs:
#   lambda_qualified_arn — versioned ARN passed to the CloudFront
#                          lambda_function_association block.
# =============================================================

# ── Variables ─────────────────────────────────────────────────────────────────

variable "environment" {
  description = "Deployment environment (dev, staging, prod)"
  type        = string
}

variable "region" {
  description = "AWS region of the Cognito User Pool"
  type        = string
  default     = "us-east-1"
}

variable "user_pool_id" {
  description = "Cognito User Pool ID"
  type        = string
}

variable "client_id" {
  description = "Cognito App Client ID (public client)"
  type        = string
}

variable "cognito_domain" {
  description = "Cognito Hosted UI domain prefix (e.g. my-app-auth-dev)"
  type        = string
}

variable "oauth_scopes" {
  description = "Space-separated OAuth scopes (e.g. 'openid email phone')"
  type        = string
  default     = "openid email phone"
}

# ── IAM Role ──────────────────────────────────────────────────────────────────

resource "aws_iam_role" "lambda_edge" {
  name = "auth-edge-${var.environment}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "LambdaEdgeTrust"
        Effect = "Allow"
        Principal = {
          Service = [
            "lambda.amazonaws.com",
            "edgelambda.amazonaws.com"
          ]
        }
        Action = "sts:AssumeRole"
      }
    ]
  })

  tags = {
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

resource "aws_iam_role_policy_attachment" "lambda_edge_basic_exec" {
  role       = aws_iam_role.lambda_edge.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# Allow writing CloudWatch Logs in any region (Lambda@Edge replicates globally)
resource "aws_iam_role_policy" "lambda_edge_logs" {
  name = "auth-edge-logs-${var.environment}"
  role = aws_iam_role.lambda_edge.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = "arn:aws:logs:*:*:*"
      }
    ]
  })
}

# ── Generate config.js ────────────────────────────────────────────────────────
#
# Lambda@Edge does not support environment variables.
# We bake the Cognito configuration directly into a config.js file
# that is zipped alongside index.js.

locals {
  config_js_content = <<-EOT
    'use strict';
    // Auto-generated by Terraform — do not edit manually.
    module.exports = {
      REGION:         '${var.region}',
      USER_POOL_ID:   '${var.user_pool_id}',
      CLIENT_ID:      '${var.client_id}',
      COGNITO_DOMAIN: '${var.cognito_domain}',
      SCOPES:         '${var.oauth_scopes}',
    };
  EOT
}

# ── Zip archive ───────────────────────────────────────────────────────────────

data "archive_file" "lambda_zip" {
  type        = "zip"
  output_path = "${path.module}/dist/auth-edge.zip"

  # index.js lives in the repository root under lambda/auth-edge/
  # path.module = infrastructures/modules/lambda-edge/
  # so ../../../lambda/auth-edge/index.js resolves correctly.
  source {
    content  = file("${path.module}/../../../lambda/auth-edge/index.js")
    filename = "index.js"
  }

  # config.js is generated above — values injected at terraform apply time
  source {
    content  = local.config_js_content
    filename = "config.js"
  }
}

# ── Lambda function ───────────────────────────────────────────────────────────
#
# Notes:
#   • Lambda@Edge MUST be deployed in us-east-1 (enforced by CloudFront).
#   • `publish = true` creates a numbered version; CloudFront requires a
#     qualified (versioned) ARN — $LATEST is not accepted.
#   • No environment variables block — not supported by Lambda@Edge.
#   • Memory / timeout limits for Viewer Request: 128 MB / 5 s.

resource "aws_lambda_function" "auth_edge" {
  filename         = data.archive_file.lambda_zip.output_path
  source_code_hash = data.archive_file.lambda_zip.output_base64sha256

  function_name = "auth-edge-${var.environment}"
  role          = aws_iam_role.lambda_edge.arn
  handler       = "index.handler"
  runtime       = "nodejs18.x"

  # Required: Lambda@Edge needs a published version, not $LATEST
  publish = true

  memory_size = 128
  timeout     = 5

  tags = {
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# ── Outputs ───────────────────────────────────────────────────────────────────

output "lambda_qualified_arn" {
  description = "Versioned Lambda ARN for use in CloudFront lambda_function_association"
  value       = aws_lambda_function.auth_edge.qualified_arn
}

output "lambda_function_name" {
  description = "Lambda function name"
  value       = aws_lambda_function.auth_edge.function_name
}

output "lambda_version" {
  description = "Published Lambda version number"
  value       = aws_lambda_function.auth_edge.version
}
